CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, username citext UNIQUE NOT NULL, password_hash text NOT NULL, totp_secret_encrypted text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS entries (id uuid PRIMARY KEY, author_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL CHECK (kind IN ('note','article')), status text NOT NULL CHECK (status IN ('draft','published','trashed')), visibility text NOT NULL CHECK (visibility IN ('public','private')), title text, slug text, summary text, markdown text NOT NULL, rendered_html text NOT NULL DEFAULT '', plain_text text NOT NULL DEFAULT '', journal_date date NOT NULL, journal_time time, time_precision text NOT NULL CHECK (time_precision IN ('day','minute')), day_position integer NOT NULL DEFAULT 0, revision bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS previous_status text;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS previous_visibility text;
CREATE UNIQUE INDEX IF NOT EXISTS entries_public_article_slug_uq ON entries (lower(slug)) WHERE kind='article' AND status='published' AND slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS entries_public_timeline_idx ON entries (journal_date DESC, journal_time ASC NULLS FIRST, day_position, id) WHERE status='published';
CREATE TABLE IF NOT EXISTS entry_working_copies (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users(id), entry_id uuid REFERENCES entries(id), client_draft_id text NOT NULL UNIQUE, base_revision bigint NOT NULL DEFAULT 0, payload jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS entry_versions (id uuid PRIMARY KEY, entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, version_no integer NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(entry_id,version_no));
CREATE TABLE IF NOT EXISTS categories (id uuid PRIMARY KEY, name text NOT NULL, slug text UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tags (id uuid PRIMARY KEY, display_name text NOT NULL, normalized_name text UNIQUE NOT NULL, slug text NOT NULL);
CREATE TABLE IF NOT EXISTS entry_categories (entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, category_id uuid NOT NULL REFERENCES categories(id) ON DELETE CASCADE, PRIMARY KEY(entry_id, category_id));
CREATE TABLE IF NOT EXISTS entry_tags (entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, tag_id uuid NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(entry_id, tag_id));
CREATE TABLE IF NOT EXISTS media (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users(id), provider text NOT NULL, visibility text NOT NULL, storage_path text, provider_key text, public_url text, original_name text NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL, sha256 text, status text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS media_refs (entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, media_id uuid NOT NULL REFERENCES media(id) ON DELETE CASCADE, PRIMARY KEY(entry_id,media_id));
CREATE TABLE IF NOT EXISTS entry_slug_history (old_slug text PRIMARY KEY, entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS site_settings (key text PRIMARY KEY, value jsonb NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_preferences (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, value jsonb NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS entries_trashed_idx ON entries(deleted_at) WHERE status='trashed';
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), token_hash text UNIQUE NOT NULL, csrf_token_hash text NOT NULL, last_seen timestamptz NOT NULL, idle_expires timestamptz NOT NULL, absolute_expires timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS mfa_challenges (token_hash text PRIMARY KEY, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS undo_tokens (token_hash text PRIMARY KEY, entry_id uuid NOT NULL REFERENCES entries(id) ON DELETE CASCADE, payload jsonb NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz);
CREATE TABLE IF NOT EXISTS exports (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users(id), export_type text NOT NULL CHECK (export_type IN ('public','full')), status text NOT NULL CHECK (status IN ('queued','running','ready','failed')), storage_path text, sha256 text, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS exports_owner_idx ON exports(owner_id, created_at DESC);
CREATE TABLE IF NOT EXISTS jobs (id bigserial PRIMARY KEY, type text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'queued', priority integer NOT NULL DEFAULT 0, run_at timestamptz NOT NULL DEFAULT now(), attempts integer NOT NULL DEFAULT 0, locked_at timestamptz, locked_by text, error text);
CREATE INDEX IF NOT EXISTS jobs_queue_idx ON jobs(status, run_at, priority DESC, id);
