apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timeblog-ci
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - configmap.yaml
  - networkpolicy.yaml
  - deployment.yaml
